[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "betterproto[compiler]>=1.2.5",
    "confluent-kafka>=2.15.0",
    "grpclib>=0.4.9",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "sentence-transformers>=5.6.1",
]
