[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "confluent-kafka>=2.15.0",
    "grpclib>=0.4.9",
    "protobuf",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "sentence-transformers>=5.6.1",
]

[dependency-groups]
dev = [
    "protoc-gen-py",
    "buf-bin",
]
