import { z } from 'zod';

export const SearchPropertySchema = z.object({
  query: z.string().min(3).max(500, "Search query is too long"),
  limit: z.int().positive().default(10),
  city: z.string().optional(),
});

export type SearchPropertyRequest = z.infer<typeof SearchPropertySchema>;

export const IngestPropertySchema = z.object({
  property_id: z.uuidv7(),
  city: z.string().min(2),
  pin_code: z.string().length(6),
  state: z.string(),
  price_cr: z.number().positive(),

  address: z.string().optional(),
  society_name: z.string().min(2).optional(),
  locality: z.string().min(2).optional(),
  city_tier: z.int().min(0).max(2).optional(),
  price_per_sqft: z.number().positive().optional(),
  bhk: z.int().positive().optional(),
  carpet_area_sqft: z.int().positive().optional(),
  property_type: z.int().nonnegative().optional(),

  latitude: z.number().optional(),
  longitude: z.number().optional(),
  zone: z.string().optional(),
  landmark: z.string().optional(),
  maintenance_monthly: z.number().nonnegative().optional(),
  maintenance_cycle: z.string().optional(),
  property_tax_yearly: z.number().nonnegative().optional(),
  stamp_duty_est: z.number().nonnegative().optional(),
  registration_fees_est: z.number().nonnegative().optional(),
  booking_amount: z.number().nonnegative().optional(),
  expected_rental_yield: z.number().nonnegative().optional(),
  is_negotiable: z.boolean().optional(),
  bathrooms: z.int().nonnegative().optional(),
  balconies: z.int().nonnegative().optional(),
  super_built_up_area_sqft: z.int().positive().optional(),
  plot_area_sqft: z.int().nonnegative().optional(),
  length_ft: z.number().nonnegative().optional(),
  width_ft: z.number().nonnegative().optional(),
  floor_number: z.int().optional(),
  total_floors: z.int().positive().optional(),
  facing_direction: z.int().nonnegative().optional(),
  furnishing_status: z.int().nonnegative().optional(),
  water_supply: z.int().nonnegative().optional(),
  flooring_type: z.int().nonnegative().optional(),
  possession_status: z.int().nonnegative().optional(),
  power_backup: z.int().nonnegative().optional(),
  ownership_type: z.int().nonnegative().optional(),
  rera_status: z.int().nonnegative().optional(),
  khata_type: z.string().optional(),

  has_pooja_room: z.boolean().optional(),
  has_servant_room: z.boolean().optional(),
  has_study_room: z.boolean().optional(),
  has_store_room: z.boolean().optional(),
  has_private_terrace: z.boolean().optional(),
  has_private_garden: z.boolean().optional(),
  has_basement: z.boolean().optional(),
  is_duplex: z.boolean().optional(),
  is_corner_plot: z.boolean().optional(),
  has_modular_kitchen: z.boolean().optional(),

  covered_parking_spots: z.int().nonnegative().optional(),
  open_parking_spots: z.int().nonnegative().optional(),
  has_ev_charging: z.boolean().optional(),
  has_visitor_parking: z.boolean().optional(),
  number_of_lifts: z.int().nonnegative().optional(),
  service_lifts: z.int().nonnegative().optional(),
  has_stp: z.boolean().optional(),
  has_rainwater_harvesting: z.boolean().optional(),
  has_solar_panels: z.boolean().optional(),
  has_piped_gas: z.boolean().optional(),

  has_swimming_pool: z.boolean().optional(),
  has_gymnasium: z.boolean().optional(),
  has_clubhouse: z.boolean().optional(),
  has_kids_play_area: z.boolean().optional(),
  has_jogging_track: z.boolean().optional(),
  has_tennis_court: z.boolean().optional(),
  has_badminton_court: z.boolean().optional(),
  has_squash_court: z.boolean().optional(),
  has_indoor_games: z.boolean().optional(),
  has_mini_theatre: z.boolean().optional(),

  has_pharmacy: z.boolean().optional(),
  has_atm: z.boolean().optional(),
  has_grocery_store: z.boolean().optional(),
  has_clinic: z.boolean().optional(),
  has_creche: z.boolean().optional(),
  has_salon: z.boolean().optional(),
  has_dog_park: z.boolean().optional(),
  has_library: z.boolean().optional(),
  has_banquet_hall: z.boolean().optional(),
  has_temple: z.boolean().optional(),

  has_24x7_security: z.boolean().optional(),
  has_cctv: z.boolean().optional(),
  has_intercom: z.boolean().optional(),
  has_video_door_phone: z.boolean().optional(),
  has_biometric_access: z.boolean().optional(),
  has_fire_alarm: z.boolean().optional(),
  has_fire_extinguishers: z.boolean().optional(),
  is_gated_community: z.boolean().optional(),
  has_guard_room: z.boolean().optional(),
  has_boom_barrier: z.boolean().optional(),

  distance_metro_km: z.number().nonnegative().optional(),
  distance_airport_km: z.number().nonnegative().optional(),
  distance_hospital_km: z.number().nonnegative().optional(),
  distance_school_km: z.number().nonnegative().optional(),
  distance_mall_km: z.number().nonnegative().optional(),
  distance_bus_stop_km: z.number().nonnegative().optional(),
  walkability_score: z.number().nonnegative().optional(),
  safety_score: z.number().nonnegative().optional(),
  livability_score: z.number().nonnegative().optional(),
  green_cover_score: z.number().nonnegative().optional(),
});

export type IngestPropertyRequest = z.infer<typeof IngestPropertySchema>;
