global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'engine'
    static_configs:
      - targets: ['engine:8000']
